services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3.19}
    depends_on:
      - mysql
      - postgresql

  mysql:
    build:
      context: ./
      dockerfile: docker/databases/mysql/Dockerfile
      args:
        - VERSION=${MYSQL_VERSION:-8.0.41}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laminasdb_test}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-yes}

  postgresql:
    build:
      context: ./
      dockerfile: docker/databases/postgresql/Dockerfile
      args:
        - VERSION=${VERSION:-17.4}
        - ALPINE_VERSION=${ALPINE_VERSION:-3.21}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-laminasdb_test}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}