= What is laminas-db?
:tabledatagateway-definition: https://www.martinfowler.com/eaaCatalog/tableDataGateway.html
:rowdatagateway-definition: https://martinfowler.com/eaaCatalog/rowDataGateway.html
:ibmdb2-driver: https://www.php.net/manual/en/intro.ibm-db2.php

Laminas-db simplifies database interaction in your PHP projects, providing a unified, programmatic interface for working with databases.
It avoids the need for you to hand-craft SQL, letting you build objects that construct SQL for you instead.

The project provides database, SQL, and result set abstraction layers, a {rowdatagateway-definition}[Row data gateway] and {tabledatagateway-definition}[Table data gateway] implementation, plus so much more.

Before we dive deeper let's quickly consider four solid reasons why laminas-db is an excellent choice for your project.

== Why would you use laminas-db?

PHP is not lacking in packages that provide database support.
There's the https://www.doctrine-project.org/projects/doctrine-dbal/en/4.3/index.html[Doctrine (database abstraction layer)], https://laravel.com/docs/12.x/eloquent[Laravel's Eloquent], and https://propelorm.org/[Propel] to name but a few of the better known ones.
Well, here are a few solid reasons why it's worth using laminas-db.

=== It's pretty quick and easy to learn

Assuming that you have a basic understanding of SQL (https://en.wikipedia.org/wiki/SQL-92[92] or above) and OOP (object-oriented programming) in PHP, then you should be able to get up and running with laminas-db pretty quickly.
This is because most of the classes model some aspect of SQL.

For example, if you need to build a select, insert, update, or delete query, there are xref:sql.adoc[the Select, Insert, Update, and Delete objects].
If you need to create, alter, and drop tables, there are xref:sql-ddl.adoc[the CreateTable, AlterTable, and DropTable objects].
What's more, where applicable, they're all designed to work with one another.

=== It provides significant flexibility

While OOP is the most common way to use the library, you don't have to use an object for every operation.
For example, you can build queries using objects, or a combination of objects and free form strings if that's what you prefer.
The library works with you, not against you.

Take the following, quite basic, SQL query as an example:

[source,sql]
----
SELECT first_name, last_name, email_address
FROM users
WHERE dob >= "2006.04.05";
----

In the above SQL query, we're retrieving the first name, last name, and email address of every user from the users table whose date of birth was on or after the 5th of April, 2006.

Here's how we could write it with objects:

[source,sql]
----
use Laminas\Db\Sql\Sql;

$sql    = new Sql($adapter);
$select = $sql->select();
$select->from('users');
$select->columns(['first_name', 'last_name', 'email_address']);
$select->where(['dob' >= "2006.04.05"]);
----

In the above example, you can see an example of instantiating a `Select` object that queries the "users" table for the required columns, where https://www.geeksforgeeks.org/sql/sql-where-clause/[the where clause] is defined using a plain PHP associative array. 

// Eventually, link `Where` to the relevant section of the docs
However, we could get a little fancier by defining the where clause using a `Where` object instead, as in the following example.

[source,php]
----
use Laminas\Db\Sql\Sql;

$sql    = new Sql($adapter);
$select = $sql->select();
$select->from('users');
$select->columns(['first_name', 'last_name', 'email_address']);
$select->where(['dob' >= "2006.04.05"]);
----

While these two examples are quite simplistic, they hint at what is possible with the library.

=== Clear code. No magic

There's nothing magic about how laminas-db works.
It only runs the queries that you ask it to run, as *you* asked it to run them.
It doesn't add extra columns to your queries.
It doesn't run nested queries without your knowledge.
It doesn't attempt to be smart on your behalf.

Sure, that might mean that there's a bit more work for you to do.
But, at all times, you know what's going on.

=== It's community-driven

Since its inception, laminas-db has been an open source, community driven and lead project.
It was designed and developed *by* developers *for* developers, to be a programmatic way of building and running SQL queries, against a range of database vendors.

Given that, you can view its entire history on GitHub, and contribute to it, as and when you find a bug or missing feature that you want to implement.
You're able to influence its direction.
You don't need to wait for it to come to you.

== laminas-db's architecture

=== Laminas\Db\Adapter\Adapter

It all starts with `Laminas\Db\Adapter\Adapter`, which is laminas-db's central object.
It is responsible for adapting any code written in or for laminas-db to the targeted PHP extensions and vendor databases; these are:

.The list of officially supported drivers
[cols="25h,~",%autowidth,stripes=even,options="header"]
|===
|Database
|PHP Extension/Driver

|IBM Db2
|The {ibmdb2-driver}[ext/ibm_db2 driver]

|MySQL
|The https://www.php.net/manual/en/intro.mysqli.php[ext/mysqli driver] and the https://www.php.net/manual/en/ref.pdo-mysql.php[Pdo_Mysql PDO extension]

|Oracle
|The https://www.php.net/manual/en/intro.oci8.php[ext/oci8 driver]

|PostgreSQL
|The https://www.php.net/manual/en/intro.pgsql.php[ext/pgsql driver] and the https://www.php.net/manual/en/ref.pdo-pgsql.php[Pdo_Pgsql PDO extension]

|Microsoft SQLServer
|The https://www.php.net/manual/en/intro.sqlsrv.php[ext/sqlsrv driver]

|SQLite
|The https://www.php.net/manual/en/ref.pdo-sqlite.php[Pdo_Sqlite PDO extension]
|===

It creates an abstraction layer for the PHP extensions in the `Driver` sub-namespace of `Laminas\Db\Adapter`.
It also creates a lightweight "Platform" abstraction layer, for the various idiosyncrasies that each vendor-specific platform might have in its SQL/RDBMS implementation, separate from the driver implementations.

=== \Laminas\Db\Adapter\Platform\AbstractPlatform

The Platform abstraction layer is based on AbstractPlatform.
It’s from this class that a vendor-specific abstraction is created.
